### ISSUE TITLE
Safari scaling issue

### ISSUE THREAD

**Issue by kamishirorui** [proNestorAps/react-zoom-pan-pinch#53]
Seems like this has been a long time issue since the old repo, and theres already a PR that I assume fixes it? https://github.com/prc5/react-zoom-pan-pinch/pull/287 

Would you mind checking it out to see if it can be implemented, thanks!

**Comment by janaagaard75** [comment]
Thanks for pointing this out, @kamishirorui. I will try to look into this, this week. This might also fix [the issue with large images](https://github.com/proNestorAps/react-zoom-pan-pinch/issues/47).

**Comment by kamishirorui** [comment]
No worries! Thanks for maintaining the library as well~

**Comment by lukaszolek** [comment]
We have the same issue, it would help us a lot to fix it. Looking forward for merging the PR. Thanks!

**Comment by janaagaard75** [comment]
Version 2.4.0 is finally out with this change - thanks for your patience. I've taken the liberty to close this issue now - please open it again, if it still hasn't been fixed.

**Comment by janaagaard75** [comment]
The `dist` folder is missing in version 2.4.0. Version 2.4.1 is out now, fixing this.
