### ISSUE TITLE
Keep content in the top-left corner

### ISSUE THREAD

**Issue by myrorr** [proNestorAps/react-zoom-pan-pinch#55]
I'm trying to use this library for a huge component and if I use the button that calls the zoomOut() function, all of my content jumps to the center to which I have to scroll. Is there a way or a setting that would always keep my content in the top left? Tried playing around with the options but haven't found anything yet.

**Comment by janaagaard75** [comment]
Can you describe a bit more in details what you are experiencing, perhaps with a step-by-step description? I cannot reproduce the issue. Does it only happen with a big component?

**Comment by janaagaard75** [comment]
I'll close this issues @myrorr since I haven't heard back. Please open it again once you have more info.
